<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <FileVersion>1.0.0</FileVersion>
    <AssemblyVersion>1.0.0</AssemblyVersion>
    <PackageVersion>1.0.0</PackageVersion>
    <Title>DarkBoy.DarkWS.Redis</Title>
    <Authors>DarkBoy</Authors>
    <Copyright>DarkBoy</Copyright>
    <Description>Redis backplane for DarkBoy.DarkWS</Description>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <PackageReadmeFile>readme.md</PackageReadmeFile>
    <TargetFrameworks>net8.0;net9.0;net10.0</TargetFrameworks>
  </PropertyGroup>
  <ItemGroup>
    <None Include="readme.md" Pack="true" PackagePath="\" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="StackExchange.Redis" Version="2.13.17" />
    <ProjectReference Include="..\DarkBoy.DarkWS\DarkBoy.DarkWS.csproj" />
  </ItemGroup>
  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>
</Project>
