<Project>
  <PropertyGroup>
    <VersionPrefix>2.1.0</VersionPrefix>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <LangVersion>default</LangVersion>
    <TargetFrameworks>net8.0;net9.0;net10.0</TargetFrameworks>
    <Deterministic>true</Deterministic>
    <ContinuousIntegrationBuild Condition="'$(CI)' == 'true'">true</ContinuousIntegrationBuild>
  </PropertyGroup>
  <PropertyGroup Condition="$(MSBuildProjectName.EndsWith('.Test'))">
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>
  <PropertyGroup Condition="'$(MSBuildProjectName)' == 'DarkWS' Or '$(MSBuildProjectName)' == 'DarkWS.Redis'">
    <Authors>Bobsans</Authors>
    <Copyright>Bobsans</Copyright>
    <PackageProjectUrl>https://github.com/Bobsans/DarkWS</PackageProjectUrl>
    <RepositoryUrl>https://github.com/Bobsans/DarkWS.git</RepositoryUrl>
    <RepositoryType>git</RepositoryType>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <PackageReadmeFile>readme.md</PackageReadmeFile>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <IncludeSymbols>true</IncludeSymbols>
    <SymbolPackageFormat>snupkg</SymbolPackageFormat>
    <PublishRepositoryUrl>true</PublishRepositoryUrl>
    <EmbedUntrackedSources>true</EmbedUntrackedSources>
    <EmbedAllSources>true</EmbedAllSources>
    <WarningsAsErrors>$(WarningsAsErrors);RS0016;RS0017;RS0024;RS0025;RS0036;RS0037;RS0048;RS0050</WarningsAsErrors>
  </PropertyGroup>
  <ItemGroup Condition="'$(MSBuildProjectName)' == 'DarkWS' Or '$(MSBuildProjectName)' == 'DarkWS.Redis'">
    <PackageReference Include="Microsoft.CodeAnalysis.PublicApiAnalyzers" PrivateAssets="all" />
    <None Include="readme.md" Pack="true" PackagePath="\" />
  </ItemGroup>
</Project>
