<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <Title>DarkWS</Title>
    <Authors>Bobsans</Authors>
    <Copyright>Bobsans</Copyright>
    <Description>Websocket server DarkWs protocol for ASP.NET</Description>
    <PackageProjectUrl>https://github.com/Bobsans/DarkWS</PackageProjectUrl>
    <RepositoryUrl>https://github.com/Bobsans/DarkWS.git</RepositoryUrl>
    <RepositoryType>git</RepositoryType>
    <PackageTags>websocket;aspnetcore;realtime;rpc</PackageTags>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <PackageReadmeFile>readme.md</PackageReadmeFile>
    <LangVersion>default</LangVersion>
    <TargetFrameworks>net8.0;net9.0;net10.0</TargetFrameworks>
  </PropertyGroup>

  <ItemGroup>
    <None Include="readme.md" Pack="true" PackagePath="\"/>
  </ItemGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App"/>
  </ItemGroup>
</Project>
