<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <Title>DarkWS</Title>
    <Description>Websocket server DarkWs protocol for ASP.NET</Description>
    <PackageTags>websocket;aspnetcore;realtime;rpc</PackageTags>
  </PropertyGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App"/>
  </ItemGroup>
</Project>
