<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <Title>DarkWS.Redis</Title>
    <Description>Redis backplane for DarkWS</Description>
    <PackageTags>websocket;aspnetcore;redis;backplane;realtime</PackageTags>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="StackExchange.Redis" />
    <ProjectReference Include="..\DarkWS\DarkWS.csproj" />
  </ItemGroup>
</Project>
